### ISSUE TITLE
No module named 'codes.threshold'

### ISSUE THREAD

**Issue by Arfinul** [deepakrana47/Wheat-quality-detector-2#1]
Modules like codes, Area and _8connected not found

**Comment by deepakrana47** [comment]
I will see the problem in two days.

**Comment by deepakrana47** [comment]
I am looking into the problem it may take some time (around 2 days), so wait for the time being.

**Comment by deepakrana47** [comment]
@Arfinul the changes has been done you can test now.

**Comment by himanshuhemu** [comment]
Still Modules like codes, Area and _8connected not found !!

**Comment by deepakrana47** [comment]
can you provide the python file name on which you are getting the error

**Comment by himanshuhemu** [comment]
no module named threshold

**Comment by deepakrana47** [comment]
try after pulling the git repo. As, at my end code is working just fine.

**Comment by himanshuhemu** [comment]
I'm getting an import error of threshold module while running cmd_wheat_quality_detector_v2.py

**Comment by himanshuhemu** [comment]
![screenshot from 2018-11-12 10-31-50](https://user-images.githubusercontent.com/30832186/48327983-cd964f00-e667-11e8-8ad8-e2f25c7abb97.png)

**Comment by himanshuhemu** [comment]
![screenshot from 2018-11-12 10-31-50](https://user-images.githubusercontent.com/30832186/48328047-249c2400-e668-11e8-919c-4c9ee3bcf6b1.png)

**Comment by deepakrana47** [comment]
I have pushed the new code, you can test it now.

**Comment by himanshuhemu** [comment]
Okkayy sir, i will try now ....thanx a lot sir , lit of things learnt from
you

**Comment by Arfinul** [comment]
Thank you for sharing all required modules to execute.

I have Python 2.7.15 installed on window 10
But can't install "tensorflow", as tensorflow doesn't support python2.7 on windows.

Tried to execute on Python3, after doing some change like printing format etc..
But getting error :
![image](https://user-images.githubusercontent.com/29590484/48348085-46b49700-e6a6-11e8-83df-9b13c359ab75.png)

**Comment by deepakrana47** [comment]
I will look into the problem and get back to you.

**Comment by Arfinul** [comment]
I think if I will generate "weights_30_30_.h5" model file, with the environment installed.
Then it will work.
But I am not able to file the module to generate this model file.

The same issue was there with "grain_feature.pkl", but i regenerated it and it worked.

Can you please share the python module generating this model file ("weights_30_30_.h5) ?

**Comment by deepakrana47** [comment]
classifier_2_v5.py and classifier_2_v2.py are used for generation of weight_30_30_.h5 file

**Comment by Arfinul** [comment]
Thanks to reply.
But, which python file I should execute for generating "weight_30_30_.h5 file" ?

**Comment by deepakrana47** [comment]
execute this file "classifier_2_v2.py"

**Comment by Arfinul** [comment]
I executed but this is creating .h5 file of the classifier.
But there is need of creating .h5 file of the segmentation data that will help in 2nd level segmentation.

How to create this file - segmentation_data/weights_30_30_.h5 ?

**Comment by Arfinul** [comment]
Model files uploaded before:
 segmentation_data/weights_30_30_.h5
 weights_results_2out/weights_01234567.pkl

Now, executed "classifier_2_v2.py", and created "weights_01234567.h5", before was creating "weights_01234567.pkl"

Model files now are as below:
'segmentation_data/weights_01234567.h5'
 weights_results_2out/weights_01234567.h5'

Stuck at 2nd level Segmentation, Please Suggest ...

![image](https://user-images.githubusercontent.com/29590484/48397146-d740b500-e742-11e8-8786-8b9d276e5de6.png)

**Comment by deepakrana47** [comment]
@Arfinul I had added the "Number_grain_detect.py" and dataset (segmentation_data/boundry_1_30.pkl and segmentation_data/boundry_2_30.pkl). "Number_grain_detect.py" file is used for generating "segmentation_data/weights_30_30_.h5".

for level 2 segmentation you can go through my paper (https://www.ijeecse.com/V5N1-023.pdf).

**Comment by Arfinul** [comment]
Thank's to share.
Now as i expected, getting an error as below.
![image](https://user-images.githubusercontent.com/29590484/48403541-14fa0980-e754-11e8-86f7-74c4523436c7.png)
As, "boundry_1_30.pkl" and "boundry_2_30.pkl" has been created in your system environment.
Hence, not getting executed in my system environment(having tensorflow python3 ).

Kindly share the file to create "boundry_1_30.pkl" and "boundry_2_30.pkl", so that i can create them in my system environment.

**Comment by deepakrana47** [comment]
"boundry_1_30.pkl" and "boundry_2_30.pkl" these two file i had already shared (present in segmentation_data/ ). The problem is arise due to opening python2.7 pickle file in python3. 

for opening python 2.7 pickle file in python3
Replace following:
      oneGrain_list = pickle.load(open(oneGrain, 'rb'))
by this:
      oneGrain_list = pickle.load(open(oneGrain, 'rb'), encoding='latin')

**Comment by qwerty020** [comment]
Able to execute now.

**Comment by Arfinul** [comment]
Fixed - Executed successfully
Thank you..

**Comment by deepakrana47** [comment]
if you are using this project some where please mention  this refrence also

"Rana, D.S., Segmentation of Overlapping Wheat Grains for Quality Detection"

**Comment by Arfinul** [comment]
For sure. 
Will definitely add your paper as a reference, As your code and paper have participated in understanding the approach and is the latest too.
Having some research idea on this topic. Working on the same.
Will contact you for any suggestion.
Thank you
