### ISSUE TITLE
Incorrect result for "test.jpg"

### ISSUE THREAD

**Issue by Arfinul** [deepakrana47/Wheat-quality-detector-2#2]
![image](https://user-images.githubusercontent.com/29590484/48942952-8fdad580-ef47-11e8-8676-86087426d555.png)

**Comment by deepakrana47** [comment]
which file you executed? (classifier_2_v2.py or classifier_5_v2.py)

**Comment by Arfinul** [comment]
classifier_2_v2.py

Checked in Ubuntu, got the result as below:
![image](https://user-images.githubusercontent.com/29590484/48965919-1dbccc00-efed-11e8-8a62-48d7cdd10d1e.png)
So, no issue on it now.
But getting the wrong result in windows as displayed in the last comment.

How can we classify the grains in 5 classes using "classifier_5_v2.py", as the main file "cmd_wheat_quality_detector_v2" is classifying grain and not grain ?

**Comment by deepakrana47** [comment]
you have to make changes in "cmd_wheat_quality_detector_v2" 
at line 20:
   "model = keras.models.load_model('weights_results_2out/weights_01234567.pkl')"
by
  "model = keras.models.load_model('weights_results_5out/weights_01234567.pkl')"
.

**Comment by deepakrana47** [comment]
If your issue is resolved Can you please close it.
